name: Cypress Tests

on:
  push:
    branches:
      - main
      - integration_testing
      - use_pnpm

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_URL: 'https://daily-joke.vercel.app'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Add cache for Cypress binary
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Run Cypress tests
        run: npx cypress run
